'use client'

import { useState, useEffect } from 'react'
import Icon from '@/components/Icon'
import { resourceApi } from '@/lib/api'
import { getStudentId } from '@/lib/student'
import ResourceCard from '../components/ResourceCard'
import type { ResourceItem } from '@/app/resources/types'

export default function MyResourcesPage() {
  const [resources, setResources] = useState<ResourceItem[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')

  const studentId = getStudentId()

  useEffect(() => {
    loadResources()
  }, [])

  const loadResources = async () => {
    setLoading(true)
    setError('')
    try {
      const data = await resourceApi.list(studentId)
      // 过滤掉系统自动生成的资源，只显示用户主动创建的资源
      const userResources = data.filter(r => {
        // 排除预设资源
        if (r.is_preset) return false
        // 排除系统自动生成的资源（标题包含特定模式）
        const title = r.title || ''
        const autoGeneratedPatterns = [
          ' - learn阶段',
          ' - review阶段',
          ' - 代码示例',
          ' - 音频讲解',
          ' - 知识讲解',
          ' - exercise（',
          ' - code（',
          ' - audio（',
          ' - mindmap（',
          ' - explanation（',
          ' 学习材料',
        ]
        const isAutoGenerated = autoGeneratedPatterns.some(pattern => title.includes(pattern))
        if (isAutoGenerated) return false
        // 排除来自对话的资源（标题以 "chat -" 开头）
        if (title.startsWith('chat -')) return false
        return true
      })
      setResources(userResources)
    } catch (err: any) {
      setError(err.message || '加载失败')
    } finally {
      setLoading(false)
    }
  }

  const handleDeleted = (id: string) => {
    setResources(prev => prev.filter(r => r.resource_id !== id))
  }

  return (
    <div style={{ padding: '24px 32px 40px', height: 'calc(100vh - var(--header-h))', overflow: 'auto' }}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 20 }}>
        <div>
          <h2 style={{ fontSize: 20, fontWeight: 600, fontFamily: "'Newsreader', serif" }}>我的资源</h2>
          <p style={{ fontSize: 13, color: 'var(--ink-3)', marginTop: 4 }}>
            共 {resources.length} 个资源
          </p>
        </div>
        <button className="btn btn-warm" onClick={loadResources}>
          <Icon name="refresh" size={14} />
          刷新
        </button>
      </div>

      {loading && (
        <div style={{ textAlign: 'center', padding: '60px 0', color: 'var(--ink-3)' }}>
          <div className="loading-spinner" style={{ width: 24, height: 24, margin: '0 auto 12px' }} />
          加载中...
        </div>
      )}

      {error && (
        <div style={{ textAlign: 'center', padding: '40px 0', color: 'var(--danger)' }}>
          <Icon name="alertTriangle" size={24} />
          <p style={{ marginTop: 8, fontSize: 13 }}>{error}</p>
          <button className="btn btn-sm" onClick={loadResources} style={{ marginTop: 12 }}>重试</button>
        </div>
      )}

      {!loading && !error && resources.length === 0 && (
        <div style={{ textAlign: 'center', padding: '60px 0', color: 'var(--ink-3)' }}>
          <Icon name="inbox" size={40} style={{ opacity: 0.3 }} />
          <p style={{ fontSize: 14, marginTop: 12, color: 'var(--ink-2)' }}>
            暂无资源
          </p>
          <p style={{ fontSize: 12, marginTop: 4 }}>
            前往资源中心创建你的第一个资源
          </p>
        </div>
      )}

      {!loading && !error && resources.length > 0 && (
        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fill, minmax(340px, 1fr))',
          gap: 14,
        }}>
          {resources.map(r => (
            <ResourceCard key={r.resource_id} resource={r} onDeleted={handleDeleted} />
          ))}
        </div>
      )}
    </div>
  )
}
